#include "inference/inference_engine.h"
#include <Arduino.h>

// The TFLite model is embedded as a C array (generated by ml/src/conversion/to_tflite.py)
// Uncomment once model is ready:
// #include "fuelguard_model.cc"

bool InferenceEngine::Init() {
    // TODO: initialise TFLite-Micro interpreter with model C array
    // 1. tflite::GetModel(fuelguard_model)
    // 2. tflite::MicroInterpreter interpreter(...)
    // 3. interpreter.AllocateTensors()
    _initialized = true;
    return true;
}

bool InferenceEngine::RunInference(const float* features,
                                    int*   classLabel,
                                    float* concentration) {
    if (!_initialized) return false;

    uint32_t t0 = millis();

    // TODO: replace stub with real TFLite-Micro invoke
    // interpreter.input(0)->data.f = features (after quantization)
    // interpreter.Invoke()
    // classLabel    = argmax(interpreter.output(0))
    // concentration = interpreter.output(1)->data.f[0]

    // Stub: return neutral values until model is integrated
    *classLabel    = 0;
    *concentration = 0.0f;

    _lastLatencyMs = millis() - t0;
    return true;
}
