/**
 * normalization.h — On-device feature normalization + temperature compensation.
 *
 * Calibration constants (min/max) are generated by the ML pipeline and
 * stored in firmware/data/calibration.json, which is flashed to SPIFFS.
 * At startup they are loaded into these arrays.
 */

#pragma once
#include <stdint.h>

// Feature indices
#define FEAT_CAP  0
#define FEAT_OPT  1
#define FEAT_TEMP 2
#define FEAT_TOF  3
#define N_FEATURES 4

/**
 * Apply joint temperature compensation and min-max normalisation.
 *
 * @param cap_raw   Raw capacitance from FDC1004 (pF or arbitrary units)
 * @param opt_raw   Raw optical transmittance (0.0–1.0)
 * @param temp_c    Temperature in °C
 * @param tof_raw   ToF reading in µs (set to 0 if sensor not present)
 * @param out       Output float[4] of normalised features ∈ [0, 1]
 */
void NormalizeFeatures(float cap_raw, float opt_raw, float temp_c,
                        float tof_raw, float out[N_FEATURES]);

/**
 * Load calibration constants from SPIFFS file /calibration.json.
 * Call once during setup(). Falls back to compile-time defaults if file missing.
 * @return true on success
 */
bool LoadCalibration();

// Calibration constants (populated by LoadCalibration or compile-time defaults)
extern float FEAT_MIN[N_FEATURES];
extern float FEAT_MAX[N_FEATURES];
extern float REF_TEMP;
extern float TEMP_COEFF_CAP;
extern float TEMP_COEFF_OPT;
