"""
TFLite INT8 post-training quantization pipeline.

Converts a trained scikit-learn or Keras MLP model into a TFLite flatbuffer
ready for deployment with TFLite-Micro on ESP32.

Steps:
  1. Wrap sklearn MLP in a tf.Module (if needed)
  2. Convert to TFLite with full-integer quantization (INT8)
  3. Validate quantized model accuracy vs float baseline
  4. Write .tflite file to artifacts/tflite/
  5. Print C-array header snippet for embedding in firmware
"""

from __future__ import annotations

import json
import struct
from pathlib import Path

import numpy as np

ARTIFACTS  = Path(__file__).parents[2] / "artifacts"
TFLITE_DIR = ARTIFACTS / "tflite"
TFLITE_DIR.mkdir(parents=True, exist_ok=True)

try:
    import tensorflow as tf
    TF_AVAILABLE = True
except ImportError:
    TF_AVAILABLE = False
    print("[to_tflite] TensorFlow not installed. Install tensorflow to use this module.")


def sklearn_mlp_to_keras(clf, input_dim: int, n_classes: int):
    """Rebuild a trained sklearn MLPClassifier as an equivalent Keras model."""
    assert TF_AVAILABLE, "TensorFlow required"
    import tensorflow as tf

    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Input(shape=(input_dim,)))
    for i, (W, b) in enumerate(zip(clf.coefs_, clf.intercepts_)):
        activation = "relu" if i < len(clf.coefs_) - 1 else "softmax"
        layer = tf.keras.layers.Dense(W.shape[1], activation=activation)
        model.add(layer)
        model.layers[-1].set_weights([W, b])
    return model


def quantize_and_export(
    keras_model,
    representative_data: np.ndarray,
    output_name: str = "fuelguard_model",
) -> Path:
    """Full INT8 post-training quantization."""
    assert TF_AVAILABLE

    def representative_dataset():
        for sample in representative_data[:200]:
            yield [sample.reshape(1, -1).astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    out_path = TFLITE_DIR / f"{output_name}.tflite"
    out_path.write_bytes(tflite_model)
    size_kb = len(tflite_model) / 1024
    print(f"[to_tflite] Exported {out_path.name}  ({size_kb:.1f} KB)")

    if size_kb > 200:
        print(f"[WARNING] Model size {size_kb:.1f} KB exceeds 200 KB ESP32 target!")
    else:
        print(f"[to_tflite] ✓ Within 200 KB budget")

    return out_path


def generate_c_array_header(tflite_path: Path) -> Path:
    """Generate a .cc file with the model as a C byte array (for firmware embedding)."""
    data    = tflite_path.read_bytes()
    name    = tflite_path.stem
    var_name = name.replace("-", "_").replace(" ", "_")

    hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
    header = (
        f"// Auto-generated by ml/src/conversion/to_tflite.py\n"
        f"// Model: {tflite_path.name}  ({len(data)} bytes)\n\n"
        f"#include <stdint.h>\n\n"
        f"const uint8_t {var_name}[] = {{\n  {hex_bytes}\n}};\n"
        f"const unsigned int {var_name}_len = {len(data)};\n"
    )

    out = Path(__file__).parents[3] / "firmware" / "src" / f"{var_name}.cc"
    out.write_text(header)
    print(f"[to_tflite] C array header → {out}")
    return out


def validate_tflite(tflite_path: Path, X_test: np.ndarray, y_test: np.ndarray) -> float:
    """Run TFLite interpreter and return accuracy."""
    assert TF_AVAILABLE
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    inp = interpreter.get_input_details()[0]
    out = interpreter.get_output_details()[0]

    scale_in,  zp_in  = inp["quantization"]
    scale_out, zp_out = out["quantization"]

    correct = 0
    for x, y in zip(X_test, y_test):
        x_q = (x / scale_in + zp_in).astype(np.int8).reshape(inp["shape"])
        interpreter.set_tensor(inp["index"], x_q)
        interpreter.invoke()
        out_q  = interpreter.get_tensor(out["index"])
        logits = (out_q.astype(np.float32) - zp_out) * scale_out
        pred   = int(np.argmax(logits))
        correct += int(pred == int(y))

    acc = correct / len(y_test)
    print(f"[validate] TFLite INT8 accuracy: {acc:.4f}")
    return acc
